# download oh-my-zsh and plugins if not existed
export ZSH="$HOME/.oh-my-zsh"
if [ ! -d "$ZSH" ]; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended --keep-zshrc && echo -e "\n"
  git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions && echo -e "\n"
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
fi

# set vim as the default editor
export VISUAL=vim
export EDITOR=$VISUAL

# shutup zsh
unsetopt beep

# set name of the theme to load
ZSH_THEME="ys"

# make color constants available
autoload -U colors
colors

# activate plugins from oh-my-zsh
plugins=(
  zsh-autosuggestions
  zsh-syntax-highlighting
  fzf
)

# path to oh-my-zsh installation
source $ZSH/oh-my-zsh.sh

# require to install nvm first
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# replace alias modern tools
if type exa > /dev/null 2>&1; then
  alias ls='exa --all --group-directories-first'
  alias la='exa --long --all --header'
  alias tree='exa -T -l -L=2 -h -I="node_modules"'
fi

type fdfind > /dev/null 2>&1 && alias fd="fdfind"
type batcat > /dev/null 2>&1 && alias cat='batcat'
type nvim > /dev/null 2>&1 && alias vim='nvim'

alias ranger='. ranger'

# prevent accidentally clobbering files
alias rm='rm -I'
alias cp='cp -i'
alias mv='mv -i'

alias mkdir='mkdir -p'

alias cls='clear'
alias h='history'
alias j='jobs -l'
alias which='type -a'
alias ..='cd ..'

# make a more readable output
alias du='du -kh'
alias df='df -kTh'

# compile c++ source file with c++17
alias g++='g++ -std=c++17 -O2 -Wall'
